<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYT6eUx5\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYT6eUx5/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYT6eUx5.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYT6eUx5\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerYT6eUx5\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'YT6eUx5',
    'container.build_id' => '3e860a81',
    'container.build_time' => 1559657638,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYT6eUx5');
