<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMOusAcN\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMOusAcN/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMOusAcN.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMOusAcN\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerMOusAcN\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'MOusAcN',
    'container.build_id' => '48c8b6c4',
    'container.build_time' => 1556199758,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMOusAcN');
